# Generated by Django 3.2.9 on 2021-11-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('volume', models.FloatField()),
            ],
        ),
    ]
