# Generated by Django 3.2.9 on 2021-11-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RuntimeGraphs', '0004_alter_cryptodataset_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptodataset',
            name='id',
        ),
        migrations.AlterField(
            model_name='cryptodataset',
            name='date',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
