# Generated by Django 3.2.9 on 2021-11-25 09:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('RuntimeGraphs', '0006_purchase_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 25, 9, 49, 49, 850422, tzinfo=utc)),
        ),
    ]
