# Generated by Django 3.2.9 on 2021-11-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RuntimeGraphs', '0008_alter_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='btc',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='username',
            field=models.CharField(default='user1', max_length=255),
        ),
    ]
