# Generated by Django 3.2.9 on 2021-12-09 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RuntimeGraphs', '0012_auto_20211207_1639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
