# Generated by Django 3.2.9 on 2021-12-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RuntimeGraphs', '0013_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETHDataset',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('open', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('high', models.FloatField()),
                ('volume', models.FloatField()),
            ],
        ),
    ]
