# Generated by Django 3.2.10 on 2021-12-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RuntimeGraphs', '0014_ethdataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Main_Img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
